// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOo08t4dOPRhP7-AKH9Zl33DlkT3VmKlo',
    appId: '1:6384888608:web:998a26cb6fe9ad92a24545',
    messagingSenderId: '6384888608',
    projectId: 'task-app-65078',
    authDomain: 'task-app-65078.firebaseapp.com',
    storageBucket: 'task-app-65078.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuyb-Ai490IAkQjKz2Si1_NjgveJWD30',
    appId: '1:6384888608:android:a3ffd0f12c0857aea24545',
    messagingSenderId: '6384888608',
    projectId: 'task-app-65078',
    storageBucket: 'task-app-65078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBU49E2lvYfHYWOtrUeas0gfkd4FKKSAQ',
    appId: '1:6384888608:ios:4fe881ce2bcd1102a24545',
    messagingSenderId: '6384888608',
    projectId: 'task-app-65078',
    storageBucket: 'task-app-65078.appspot.com',
    iosClientId: '6384888608-fqqigvl9kv2uia1vtien07l2v5p6gj9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutterI2G5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBU49E2lvYfHYWOtrUeas0gfkd4FKKSAQ',
    appId: '1:6384888608:ios:4fe881ce2bcd1102a24545',
    messagingSenderId: '6384888608',
    projectId: 'task-app-65078',
    storageBucket: 'task-app-65078.appspot.com',
    iosClientId: '6384888608-fqqigvl9kv2uia1vtien07l2v5p6gj9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutterI2G5',
  );
}
